version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}

  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build: .
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - db
    command: ["yarn", "start:prod"]
    environment:
      - PORT=${PORT}
      - STREAMLABS_TOKEN=${STREAMLABS_TOKEN}
      - PG_HOST=db
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DATABASE=${PG_DATABASE}
